# -*- coding: utf-8 -*-
"""1_Figures.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ysb6TilBaDaJ7XquVOSkYlAZwnsjTgXe

# Chapter Results - Figures

## Used libraries
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import scipy.stats as stats
from scipy.stats import skew, kurtosis, norm, shapiro, kstest, anderson, jarque_bera
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import os
import io
from contextlib import redirect_stdout

"""## Seaborn"""

sns.set_style("whitegrid")

plt.rcParams.update({
    "figure.dpi": 300,
    "savefig.dpi": 300,

    "font.family": "sans-serif",
    "font.size": 11,

    "axes.titlesize": 16,
    "axes.titleweight": "bold",
    "axes.labelsize": 14,
    "axes.labelweight": "semibold",

    "xtick.labelsize": 11,
    "ytick.labelsize": 11,

    "xtick.major.size": 6,
    "ytick.major.size": 6,

    "xtick.minor.size": 3,
    "ytick.minor.size": 3,

    "xtick.major.width": 1,
    "ytick.major.width": 1,

    "xtick.major.pad": 3.5,
    "ytick.major.pad": 3.5,

    "xtick.direction": "out",
    "ytick.direction": "out",

    "xtick.color": "black",
    "ytick.color": "black",

    "xtick.minor.visible": False,
    "ytick.minor.visible": False,

    "xtick.top": False,
    "xtick.bottom": True,
    "ytick.left": True,
    "ytick.right": False,

    "legend.fontsize": 10,
    "legend.title_fontsize": 12,
    "legend.framealpha": 0.9,

    "figure.titlesize": 18,
    "figure.titleweight": "bold",

    "axes.linewidth": 1.0,
    "axes.edgecolor": "black",

    "axes.spines.top": True,
    "axes.spines.bottom": True,
    "axes.spines.left": True,
    "axes.spines.right": True,

    "patch.linewidth": 1.5,
    "patch.edgecolor": "black",
    "patch.facecolor": "blue",
    "patch.force_edgecolor": True,

    "axes.grid": False,
})

"""## Error Functions and Statistics"""

def analyze_distribution(_hist, save_path=None):
    """
    Analyze a distribution represented by a histogram array.

    Parameters:
    -----------
    _hist : array-like
        Array representing the distribution data
    save_path : str or None
        If provided, saves the summary figure to this path
    """

    data = np.asarray(_hist)

    print("=" * 60)
    print("DISTRIBUTION ANALYSIS REPORT")
    print("=" * 60)

    print("\n1. BASIC STATISTICS")
    print("-" * 40)
    print(f"Sample size: {len(data):,}")
    print(f"Mean: {np.mean(data):.4f}")
    print(f"Median: {np.median(data):.4f}")
    print(f"Std deviation: {np.std(data, ddof=1):.4f}")
    print(f"Variance: {np.var(data, ddof=1):.4f}")
    print(f"Min: {np.min(data):.4f}")
    print(f"Max: {np.max(data):.4f}")
    print(f"Range: {np.ptp(data):.4f}")
    print(f"IQR: {np.percentile(data, 75) - np.percentile(data, 25):.4f}")

    print("\n2. DISTRIBUTION SHAPE")
    print("-" * 40)

    skewness = skew(data, bias=False)
    print(f"Skewness: {skewness:.4f}")

    if abs(skewness) < 0.5:
        skew_interpret = "Approximately symmetric"
    elif abs(skewness) < 1:
        skew_interpret = "Moderately skewed"
    else:
        skew_interpret = "Highly skewed"

    if skewness > 0:
        skew_direction = "right (positive)"
    elif skewness < 0:
        skew_direction = "left (negative)"
    else:
        skew_direction = "no"

    print(f"  -> {skew_interpret}, {skew_direction} skew")

    kurt = kurtosis(data, bias=False, fisher=True)
    print(f"Kurtosis (excess): {kurt:.4f}")

    if abs(kurt) < 0.5:
        kurt_interpret = "Mesokurtic (similar to normal)"
    elif kurt > 0.5:
        kurt_interpret = "Leptokurtic (heavy-tailed)"
    else:
        kurt_interpret = "Platykurtic (light-tailed)"
    print(f"  -> {kurt_interpret}")

    print("\n3. COMPARISON WITH NORMAL DISTRIBUTION")
    print("-" * 40)

    mean = np.mean(data)
    std = np.std(data, ddof=1)
    normal_dist = norm(loc=mean, scale=std)

    print("\nNormality tests:")

    shapiro_stat = shapiro_p = None
    if len(data) <= 5000:
        shapiro_stat, shapiro_p = shapiro(data)
        print(f"Shapiro-Wilk test: W = {shapiro_stat:.4f}, p = {shapiro_p:.6f}")
        if shapiro_p > 0.05:
            print("  -> Cannot reject normality (p > 0.05)")
        else:
            print("  -> Distribution appears non-normal (p <= 0.05)")

    ks_stat, ks_p = kstest(data, 'norm', args=(mean, std))
    print(f"Kolmogorov-Smirnov test: D = {ks_stat:.4f}, p = {ks_p:.6f}")

    anderson_result = anderson(data, dist='norm')
    print(f"Anderson-Darling test: A^2 = {anderson_result.statistic:.4f}")

    significance_level = 0.05
    crit_value = anderson_result.critical_values[2]
    if anderson_result.statistic < crit_value:
        print(f"  -> Cannot reject normality at 5% level (A^2 < {crit_value:.4f})")
    else:
        print(f"  -> Reject normality at 5% level (A^2 >= {crit_value:.4f})")

    jb_stat, jb_p = jarque_bera(data)
    print(f"Jarque-Bera test: JB = {jb_stat:.4f}, p = {jb_p:.6f}")

    print("\nQuantile comparison (theoretical vs empirical):")
    quantiles = [0.01, 0.05, 0.25, 0.5, 0.75, 0.95, 0.99]
    print(f"{'Quantile':<10} {'Empirical':<12} {'Normal':<12} {'Difference':<12}")
    print("-" * 46)
    for q in quantiles:
        emp_q = np.percentile(data, q * 100)
        norm_q = normal_dist.ppf(q)
        diff = emp_q - norm_q
        print(f"{q:<10} {emp_q:<12.4f} {norm_q:<12.4f} {diff:<12.4f}")

    print("\n4. VISUAL ANALYSIS (check generated plots)")

    fig, axes = plt.subplots(2, 3, figsize=(15, 10))

    ax1 = axes[0, 0]
    sns.histplot(data, kde=True, ax=ax1, stat='density', color='skyblue', edgecolor='black')
    x = np.linspace(mean - 4*std, mean + 4*std, 1000)
    ax1.plot(x, normal_dist.pdf(x), 'r-', alpha=0.7, linewidth=2, label='Normal PDF')
    ax1.set_title('Histogram with Normal PDF')
    ax1.set_xlabel('Value')
    ax1.set_ylabel('Density')
    ax1.legend()

    ax2 = axes[0, 1]
    stats.probplot(data, dist="norm", plot=ax2)
    ax2.set_title('Q-Q Plot (vs Normal)')

    ax3 = axes[0, 2]
    ax3.boxplot(data, vert=True, patch_artist=True)
    ax3.set_title('Box Plot')
    ax3.set_ylabel('Value')

    ax4 = axes[1, 0]
    sorted_data = np.sort(data)
    ecdf = np.arange(1, len(sorted_data) + 1) / len(sorted_data)
    ax4.plot(sorted_data, ecdf, 'b-', linewidth=2, label='ECDF')
    ax4.plot(sorted_data, normal_dist.cdf(sorted_data), 'r--', alpha=0.7, label='Normal CDF')
    ax4.set_title('ECDF vs Normal CDF')
    ax4.set_xlabel('Value')
    ax4.set_ylabel('Cumulative Probability')
    ax4.legend()
    ax4.grid(True, alpha=0.3)

    ax5 = axes[1, 1]
    moments_data = [skewness, kurt]
    moments_normal = [0, 0]
    labels = ['Skewness', 'Excess Kurtosis']
    x_pos = np.arange(len(labels))
    width = 0.35

    ax5.bar(x_pos - width/2, moments_data, width, label='Data', color='skyblue', edgecolor='black')
    ax5.bar(x_pos + width/2, moments_normal, width, label='Normal', color='lightcoral', edgecolor='black')
    ax5.set_ylabel('Value')
    ax5.set_title('Distribution Moments Comparison')
    ax5.set_xticks(x_pos)
    ax5.set_xticklabels(labels)
    ax5.legend()
    ax5.axhline(y=0, color='black', linestyle='-', alpha=0.3)

    ax6 = axes[1, 2]
    ax6.axis('tight')
    ax6.axis('off')

    summary_data = [
        ['Statistic', 'Value'],
        ['N', f'{len(data):,}'],
        ['Mean', f'{mean:.4f}'],
        ['Std Dev', f'{std:.4f}'],
        ['Skewness', f'{skewness:.4f}'],
        ['Kurtosis', f'{kurt:.4f}'],
        ['Shapiro p', f'{shapiro_p:.4f}' if len(data) <= 5000 else 'N/A'],
        ['KS p', f'{ks_p:.4f}']
    ]

    table = ax6.table(cellText=summary_data, cellLoc='center', loc='center')
    table.auto_set_font_size(False)
    table.set_fontsize(10)
    table.scale(1.2, 1.5)
    ax6.set_title('Summary Statistics')

    plt.tight_layout()
    if save_path:
        plt.savefig(save_path)
    plt.close(fig)

    print("\n5. ADDITIONAL INSIGHTS")
    print("-" * 40)

    Q1 = np.percentile(data, 25)
    Q3 = np.percentile(data, 75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    outliers = data[(data < lower_bound) | (data > upper_bound)]

    print(f"Potential outliers (IQR method): {len(outliers)} ({len(outliers)/len(data)*100:.2f}%)")

    hist_counts, _ = np.histogram(data, bins='auto')
    hist_counts = hist_counts[hist_counts > 0]
    probabilities = hist_counts / hist_counts.sum()
    entropy = -np.sum(probabilities * np.log2(probabilities))
    print(f"Entropy: {entropy:.4f} bits")

    cv = std / mean if mean != 0 else np.inf
    print(f"Coefficient of variation: {cv:.4f}")

    print("\n" + "=" * 60)
    print("ANALYSIS COMPLETE")
    print("=" * 60)

    return {
        'mean': mean,
        'std': std,
        'skewness': skewness,
        'kurtosis': kurt,
        'normality_tests': {
            'shapiro': (shapiro_stat, shapiro_p) if len(data) <= 5000 else None,
            'ks': (ks_stat, ks_p),
            'anderson': anderson_result.statistic,
            'jarque_bera': (jb_stat, jb_p)
        },
        'outliers_count': len(outliers),
        'entropy': entropy,
        'cv': cv
    }


def calculate_mae(actual, predicted):
    actual = np.array(actual)
    predicted = np.array(predicted)
    return mean_absolute_error(actual, predicted)

def calculate_mse(actual, predicted):
    actual = np.array(actual)
    predicted = np.array(predicted)
    return mean_squared_error(actual, predicted)

def calculate_rmse(actual, predicted):
    actual = np.array(actual)
    predicted = np.array(predicted)
    return np.sqrt(mean_squared_error(actual, predicted))

def calculate_mape(actual, predicted):
    actual = np.array(actual)
    predicted = np.array(predicted)

    mask = actual != 0
    actual = actual[mask]
    predicted = predicted[mask]

    if len(actual) == 0:
        return np.inf

    return np.mean(np.abs((actual - predicted) / actual)) * 100

def calculate_r2(actual, predicted):
    actual = np.array(actual)
    predicted = np.array(predicted)
    return r2_score(actual, predicted)

calculate_ape = lambda ytrue, ypreds: (np.abs(ytrue - ypreds)/(ytrue + 1e-6)) * 100

calculate_pe = lambda ytrue, ypreds: ((ytrue - ypreds)/(ytrue + 1e-6)) * 100

def calculate_metrics(actual, predicted):
    print("Metrics")
    print(f"MAE: {calculate_mae(actual, predicted):.2f}")
    print(f"MSE: {calculate_mse(actual, predicted):.2f}")
    print(f"RMSE: {calculate_rmse(actual, predicted):.2f}")
    print(f"MAPE: {calculate_mape(actual, predicted):.2f}%")
    print(f"R2: {calculate_r2(actual, predicted):.4f}")


"""## Process a single model"""

def process_model(model_name):
    data_dir = f'./{model_name}_data'
    img_base = f'./{model_name}_images'
    stats_path = f'{img_base}/statistics.txt'

    for subdir in ['train', 'val', 'test', '145']:
        os.makedirs(f'{img_base}/{subdir}', exist_ok=True)

    stats_buffer = io.StringIO()

    with redirect_stdout(stats_buffer):
        print(f"{'='*60}")
        print(f"STATISTICS REPORT FOR: {model_name}")
        print(f"{'='*60}\n")

        print("## Data and Predictions")
        print(f"Loading data from: {data_dir}")

        true_train = np.load(f'{data_dir}/y_train.npy')
        preds_train = np.load(f'{data_dir}/preds_train.npy')
        print(f"true_train: {true_train.shape}, preds_train: {preds_train.shape}")

        true_val = np.load(f'{data_dir}/y_val.npy')
        preds_val = np.load(f'{data_dir}/preds_val.npy')
        print(f"true_val:   {true_val.shape}, preds_val:   {preds_val.shape}")

        true_test = np.load(f'{data_dir}/y_test.npy')
        preds_test = np.load(f'{data_dir}/preds_test.npy')
        print(f"true_test:  {true_test.shape}, preds_test:  {preds_test.shape}")

        true_145 = np.load(f'{data_dir}/y_145.npy')
        preds_145 = np.load(f'{data_dir}/preds_145.npy')
        print(f"true_145:   {true_145.shape}, preds_145:   {preds_145.shape}")

        # -----------------------------------------------------------------------
        # TRAIN
        # -----------------------------------------------------------------------
        print("\n\n" + "#" * 60)
        print("# TRAIN PREDICTIONS")
        print("#" * 60 + "\n")

        ape_train = calculate_ape(true_train, preds_train)
        pe_train = calculate_pe(true_train, preds_train)
        mape_train = calculate_mape(true_train, preds_train)
        print(f"MAPE train: {mape_train:.2f}%")

        plt.figure(figsize=(9, 7))
        plt.scatter(true_train, preds_train, s=1, c=ape_train, cmap='viridis')
        plt.colorbar(label='EAP [%]')
        plt.plot([x for x in range(95, 1505)], [x for x in range(95, 1505)], color='red', linestyle='--', lw=1)
        plt.vlines(100, 95, 1505, color='gray', linestyles='--', alpha=0.5, lw=1)
        plt.vlines(1500, 95, 1505, color='gray', linestyles='--', alpha=0.5, lw=1)
        plt.xlabel('Valor real del Espesor [nm]')
        plt.ylabel('Inferencia del Espesor [nm]')
        plt.savefig(f'{img_base}/train/comparsion_true_preds.png')
        plt.close()

        plt.figure(figsize=(5, 5))
        sns.kdeplot(ape_train, fill=True, color='blue', edgecolor='black', alpha=0.6, label=None, clip=[0, np.inf])
        plt.ylabel('Densidad')
        plt.xlabel('EAP [%]')
        plt.legend().remove()
        plt.savefig(f'{img_base}/train/dist_ape.png')
        plt.close()

        print("\n--- Distribution Analysis: APE (Train) ---")
        analyze_distribution(ape_train[:, 0].astype(np.float64),
                             save_path=f'{img_base}/train/dist_analysis_ape.png')

        plt.figure(figsize=(5, 5))
        sns.kdeplot(pe_train, fill=True, color='blue', edgecolor='black', alpha=0.6, label=None)
        plt.ylabel('Densidad')
        plt.xlabel('Error Porcentual [%]')
        plt.legend().remove()
        plt.savefig(f'{img_base}/train/dist_ep.png')
        plt.close()

        print("\n--- Distribution Analysis: PE (Train) ---")
        analyze_distribution(pe_train[:, 0].astype(np.float64),
                             save_path=f'{img_base}/train/dist_analysis_pe.png')

        plt.figure(figsize=(5, 5))
        sns.kdeplot(true_train[:, 0], fill=True, color='blue', edgecolor='black', alpha=0.6,
                     label='Valor Real', lw=0.1, clip=[100, 1500])
        sns.kdeplot(preds_train[:, 0], fill=True, color='red', edgecolor='black', alpha=0.4,
                     label='Inferencia', lw=0.1, clip=[100, 1500])
        plt.ylabel('Densidad')
        plt.xlabel('Espesor [nm]')
        plt.legend()
        plt.ticklabel_format(axis='y', style='sci', scilimits=(0, 0))
        plt.savefig(f'{img_base}/train/two_dist.png')
        plt.close()

        print("\n--- Metrics (Train) ---")
        calculate_metrics(true_train, preds_train)

        plt.figure(figsize=(5, 5))
        plt.scatter(true_train, ape_train, s=0.1)
        plt.xlabel('Espesor [nm]')
        plt.ylabel('EAP [%]')
        plt.hlines(np.mean(ape_train), 95, 1505, color='red', linestyle='--', label='Media', lw=1)
        plt.hlines(np.median(ape_train), 95, 1505, color='orange', linestyle='--', label='Mediana', lw=1)
        plt.vlines(100, 0, 65, color='gray', linestyles='--', alpha=0.5, lw=1)
        plt.vlines(1500, 0, 65, color='gray', linestyles='--', alpha=0.5, lw=1)
        plt.vlines(250, 0, 65, color='green', linestyles='--', alpha=0.5, lw=1)
        plt.vlines(600, 0, 65, color='green', linestyles='--', alpha=0.5, lw=1)
        plt.vlines(950, 0, 65, color='green', linestyles='--', alpha=0.5, lw=1)
        plt.vlines(1100, 0, 65, color='green', linestyles='--', alpha=0.5, lw=1)
        plt.legend()
        plt.savefig(f'{img_base}/train/error.png')
        plt.close()

        # -----------------------------------------------------------------------
        # VAL
        # -----------------------------------------------------------------------
        print("\n\n" + "#" * 60)
        print("# VAL PREDICTIONS")
        print("#" * 60 + "\n")

        ape_val = calculate_ape(true_val, preds_val)
        pe_val = calculate_pe(true_val, preds_val)
        print(f"Mean APE val: {np.mean(ape_val):.4f}")

        plt.figure(figsize=(9, 7))
        plt.scatter(true_val, preds_val, s=1, c=ape_val, cmap='viridis')
        plt.colorbar(label='EAP [%]')
        plt.plot([x for x in range(95, 1505)], [x for x in range(95, 1505)], color='red', linestyle='--', lw=1)
        plt.vlines(100, 95, 1505, color='gray', linestyles='--', alpha=0.5, lw=1)
        plt.vlines(1500, 95, 1505, color='gray', linestyles='--', alpha=0.5, lw=1)
        plt.xlabel('Valor real del Espesor [nm]')
        plt.ylabel('Inferencia del Espesor [nm]')
        plt.savefig(f'{img_base}/val/comparsion_true_preds.png')
        plt.close()

        plt.figure(figsize=(5, 5))
        sns.kdeplot(ape_val, fill=True, color='blue', edgecolor='black', alpha=0.6, label=None, clip=[0, np.inf])
        plt.ylabel('Densidad')
        plt.xlabel('EAP [%]')
        plt.legend().remove()
        plt.savefig(f'{img_base}/val/dist_ape.png')
        plt.close()

        print("\n--- Distribution Analysis: APE (Val) ---")
        analyze_distribution(ape_val[:, 0].astype(np.float64),
                             save_path=f'{img_base}/val/dist_analysis_ape.png')

        plt.figure(figsize=(5, 5))
        sns.kdeplot(pe_val, fill=True, color='blue', edgecolor='black', alpha=0.6, label=None)
        plt.ylabel('Densidad')
        plt.xlabel('Error Porcentual [%]')
        plt.legend().remove()
        plt.savefig(f'{img_base}/val/dist_pe.png')
        plt.close()

        print("\n--- Distribution Analysis: PE (Val) ---")
        analyze_distribution(pe_val[:, 0].astype(np.float64),
                             save_path=f'{img_base}/val/dist_analysis_pe.png')

        plt.figure(figsize=(5, 5))
        sns.kdeplot(true_val[:, 0], fill=True, color='blue', edgecolor='black', alpha=0.6,
                     label='Valor Real', lw=0.1, clip=[100, 1500])
        sns.kdeplot(preds_val[:, 0], fill=True, color='red', edgecolor='black', alpha=0.4,
                     label='Inferencia', lw=0.1, clip=[100, 1500])
        plt.ylabel('Densidad')
        plt.xlabel('Espesor [nm]')
        plt.legend()
        plt.ticklabel_format(axis='y', style='sci', scilimits=(0, 0))
        plt.savefig(f'{img_base}/val/two_dist.png')
        plt.close()

        print("\n--- Metrics (Val) ---")
        calculate_metrics(true_val, preds_val)

        plt.figure(figsize=(5, 5))
        plt.scatter(true_val, ape_val, s=0.1)
        plt.xlabel('Espesor [nm]')
        plt.ylabel('EAP [%]')
        plt.hlines(np.mean(ape_val), 95, 1505, color='red', linestyle='--', label='Media', lw=1)
        plt.hlines(np.median(ape_val), 95, 1505, color='orange', linestyle='--', label='Mediana', lw=1)
        plt.vlines(100, 0, 30, color='gray', linestyles='--', alpha=0.5, lw=1)
        plt.vlines(1500, 0, 30, color='gray', linestyles='--', alpha=0.5, lw=1)
        plt.vlines(250, 0, 30, color='green', linestyles='--', alpha=0.5, lw=1)
        plt.vlines(600, 0, 30, color='green', linestyles='--', alpha=0.5, lw=1)
        plt.vlines(950, 0, 30, color='green', linestyles='--', alpha=0.5, lw=1)
        plt.vlines(1100, 0, 30, color='green', linestyles='--', alpha=0.5, lw=1)
        plt.legend()
        plt.savefig(f'{img_base}/val/error.png')
        plt.close()

        # -----------------------------------------------------------------------
        # TEST
        # -----------------------------------------------------------------------
        print("\n\n" + "#" * 60)
        print("# TEST PREDICTIONS")
        print("#" * 60 + "\n")

        ape_test = calculate_ape(true_test, preds_test)
        pe_test = calculate_pe(true_test, preds_test)
        print(f"Mean APE test: {np.mean(ape_test):.4f}")

        plt.figure(figsize=(9, 7))
        plt.scatter(true_test, preds_test, s=1, c=ape_test, cmap='viridis')
        plt.colorbar(label='EAP [%]')
        plt.plot([x for x in range(95, 1505)], [x for x in range(95, 1505)], color='red', linestyle='--', lw=1)
        plt.vlines(100, 95, 1505, color='gray', linestyles='--', alpha=0.5, lw=1)
        plt.vlines(1500, 95, 1505, color='gray', linestyles='--', alpha=0.5, lw=1)
        plt.xlabel('Valor real del Espesor [nm]')
        plt.ylabel('Inferencia del Espesor [nm]')
        plt.savefig(f'{img_base}/test/comparsion_true_preds.png')
        plt.close()

        plt.figure(figsize=(5, 5))
        sns.kdeplot(ape_test, fill=True, color='blue', edgecolor='black', alpha=0.6, label=None, clip=[0, np.inf])
        plt.ylabel('Densidad')
        plt.xlabel('EAP [%]')
        plt.legend().remove()
        plt.savefig(f'{img_base}/test/dist_ape.png')
        plt.close()

        print("\n--- Distribution Analysis: APE (Test) ---")
        analyze_distribution(ape_test[:, 0].astype(np.float64),
                             save_path=f'{img_base}/test/dist_analysis_ape.png')

        plt.figure(figsize=(5, 5))
        sns.kdeplot(pe_test, fill=True, color='blue', edgecolor='black', alpha=0.6, label=None)
        plt.ylabel('Densidad')
        plt.xlabel('Error Porcentual [%]')
        plt.legend().remove()
        plt.savefig(f'{img_base}/test/dist_pe.png')
        plt.close()

        print("\n--- Distribution Analysis: PE (Test) ---")
        analyze_distribution(pe_test[:, 0].astype(np.float64),
                             save_path=f'{img_base}/test/dist_analysis_pe.png')

        plt.figure(figsize=(5, 5))
        sns.kdeplot(true_test[:, 0], fill=True, color='blue', edgecolor='black', alpha=0.6,
                     label='Valor Real', lw=0.1, clip=[100, 1500])
        sns.kdeplot(preds_test[:, 0], fill=True, color='red', edgecolor='black', alpha=0.4,
                     label='Inferencia', lw=0.1, clip=[100, 1500])
        plt.ylabel('Densidad')
        plt.xlabel('Espesor [nm]')
        plt.legend()
        plt.ticklabel_format(axis='y', style='sci', scilimits=(0, 0))
        plt.savefig(f'{img_base}/test/two_dist.png')
        plt.close()

        print("\n--- Metrics (Test) ---")
        calculate_metrics(true_test, preds_test)

        plt.figure(figsize=(5, 5))
        plt.scatter(true_test, ape_test, s=0.1)
        plt.xlabel('Espesor [nm]')
        plt.ylabel('EAP [%]')
        plt.hlines(np.mean(ape_test), 95, 1505, color='red', linestyle='--', label='Media', lw=1)
        plt.hlines(np.median(ape_test), 95, 1505, color='orange', linestyle='--', label='Mediana', lw=1)
        plt.vlines(100, 0, 45, color='gray', linestyles='--', alpha=0.5, lw=1)
        plt.vlines(1500, 0, 45, color='gray', linestyles='--', alpha=0.5, lw=1)
        plt.vlines(250, 0, 45, color='green', linestyles='--', alpha=0.5, lw=1)
        plt.vlines(600, 0, 45, color='green', linestyles='--', alpha=0.5, lw=1)
        plt.vlines(950, 0, 45, color='green', linestyles='--', alpha=0.5, lw=1)
        plt.vlines(1100, 0, 45, color='green', linestyles='--', alpha=0.5, lw=1)
        plt.legend()
        plt.savefig(f'{img_base}/test/error.png')
        plt.close()

        # -----------------------------------------------------------------------
        # 145
        # -----------------------------------------------------------------------
        print("\n\n" + "#" * 60)
        print("# 145 PREDICTIONS")
        print("#" * 60 + "\n")

        ape_145 = calculate_ape(true_145, preds_145)
        pe_145 = calculate_pe(true_145, preds_145)
        print(f"Mean APE 145: {np.mean(ape_145):.4f}")

        plt.figure(figsize=(9, 7))
        plt.scatter(true_145, preds_145, s=5, c=ape_145, cmap='viridis')
        plt.colorbar(label='EAP [%]')
        plt.plot([x for x in range(95, 1505)], [x for x in range(95, 1505)], color='red', linestyle='--', lw=1)
        plt.vlines(100, 95, 1505, color='gray', linestyles='--', alpha=0.5, lw=1)
        plt.vlines(1500, 95, 1505, color='gray', linestyles='--', alpha=0.5, lw=1)
        plt.xlabel('Valor real del Espesor [nm]')
        plt.ylabel('Inferencia del Espesor [nm]')
        plt.savefig(f'{img_base}/145/comparsion_true_preds.png')
        plt.close()

        plt.figure(figsize=(5, 5))
        sns.kdeplot(ape_145, fill=True, color='blue', edgecolor='black', alpha=0.6, label=None, clip=[0, np.inf])
        plt.ylabel('Densidad')
        plt.xlabel('EAP [%]')
        plt.legend().remove()
        plt.savefig(f'{img_base}/145/dist_epa.png')
        plt.close()

        plt.figure(figsize=(5, 5))
        sns.histplot(ape_145, bins=np.arange(0, np.max(ape_145), 1), kde=True)
        plt.ylabel('# Muestras')
        plt.xlabel('EAP [%]')
        plt.legend().remove()
        plt.savefig(f'{img_base}/145/hist.png')
        plt.close()

        print("\n--- Distribution Analysis: APE (145) ---")
        analyze_distribution(ape_145[:, 0].astype(np.float64),
                             save_path=f'{img_base}/145/dist_analysis_ape.png')

        plt.figure(figsize=(5, 5))
        sns.kdeplot(pe_145, fill=True, color='blue', edgecolor='black', alpha=0.6, label=None)
        plt.ylabel('Densidad')
        plt.xlabel('Error Porcentual [%]')
        plt.legend().remove()
        plt.savefig(f'{img_base}/145/dist_pe.png')
        plt.close()

        print("\n--- Distribution Analysis: PE (145) ---")
        analyze_distribution(pe_145[:, 0].astype(np.float64),
                             save_path=f'{img_base}/145/dist_analysis_pe.png')

        plt.figure(figsize=(5, 5))
        sns.kdeplot(true_145[:, 0], fill=True, color='blue', edgecolor='black', alpha=0.6,
                     label='Valor Real', lw=0.1, clip=[100, 1500])
        sns.kdeplot(preds_145[:, 0], fill=True, color='red', edgecolor='black', alpha=0.4,
                     label='Inferencia', lw=0.1, clip=[100, 1500])
        plt.ylabel('Densidad')
        plt.xlabel('Espesor [nm]')
        plt.legend()
        plt.ticklabel_format(axis='y', style='sci', scilimits=(0, 0))
        plt.savefig(f'{img_base}/145/two_dist.png')
        plt.close()

        print("\n--- Metrics (145) ---")
        calculate_metrics(true_145, preds_145)

        plt.figure(figsize=(5, 5))
        plt.scatter(true_145, ape_145, s=3)
        plt.xlabel('Espesor [nm]')
        plt.ylabel('EAP [%]')
        plt.hlines(np.mean(ape_145), 95, 1505, color='red', linestyle='--', label='Media', lw=1)
        plt.hlines(np.median(ape_145), 95, 1505, color='orange', linestyle='--', label='Mediana', lw=1)
        plt.vlines(100, 0, 30, color='gray', linestyles='--', alpha=0.5, lw=1)
        plt.vlines(1500, 0, 30, color='gray', linestyles='--', alpha=0.5, lw=1)
        plt.vlines(250, 0, 30, color='green', linestyles='--', alpha=0.5, lw=1)
        plt.vlines(600, 0, 30, color='green', linestyles='--', alpha=0.5, lw=1)
        plt.vlines(950, 0, 30, color='green', linestyles='--', alpha=0.5, lw=1)
        plt.vlines(1100, 0, 30, color='green', linestyles='--', alpha=0.5, lw=1)
        plt.legend()
        plt.savefig(f'{img_base}/145/error.png')
        plt.close()

        print(f"\n\n{'='*60}")
        print(f"END OF REPORT FOR: {model_name}")
        print(f"{'='*60}")

    with open(stats_path, 'w') as f:
        f.write(stats_buffer.getvalue())

    print(f"Statistics saved to {stats_path}")

    total_files = 0
    for root, dirs, files in os.walk(img_base):
        total_files += len(files)
    print(f"Total files generated in {img_base}: {total_files}")


"""## Main — Process MSE only"""

if __name__ == '__main__':
    process_model('MSE')
